<?php

return [

    'entrust' => [
    	'items' => [
    		'1' => '必PO TV網頁版',
    		'2' => '必PO TV手機版',
    		'3' => '必PO TV APP',
    		'4' => '中天影音平台專案',
    		'5' => '中天FB社群',
    		'6' => '快點TV網頁版',
    		'7' => '快點TV手機版',
    		'8' => '快點TV APP',
    		'9' => '其他專案',
    	],
    	'pay' => [
    		'請選擇',
    		'現金',
            '支票',
            '匯款',
    	],
    	'pay_status' => [
    		'首次合作，需於執行前支付兌現全額',
    		'發票日次日起算30天內支付兌現金額',
    		'依合約付款',
    	],
        'status' => [
            '0' => '取消委刊',
            '1' => '提案',
            '2' => '審核中',
            '3' => '審核通過',
            '4' => '退件',
            '5' => '暫停',
            '9' => '結案',
        ],
    ],

    'publish' => [
        'status' => [
            '0' => '尚未預約',
            '1' => '執行中',
            '2' => '已預約',
            '3' => '待執行',
        ],
        'colors' => [
            'AliceBlue' => 'DimGray',
            'AntiqueWhite' => 'DimGray',
            'Aqua' => 'DimGray',
            'Aquamarine' => 'DimGray',
            'Beige' => 'DimGray',
            'Bisque' => 'DimGray',
            'Blue' => 'white',
            'BlueViolet' => 'white',
            'Brown' => 'white',
            'BurlyWood' => 'DimGray',
            'CadetBlue' => 'white',
            'Chartreuse' => 'DimGray',
            'Chocolate' => 'white',
            'Coral' => 'white',
            'CornflowerBlue' => 'white',
            'Crimson' => 'white',
            'Cyan' => 'DimGray',
            'DarkBlue' => 'white',
            'DarkCyan' => 'white',
            'DarkGoldenRod' => 'white',
            'DarkGreen' => 'white',
            'DarkKhaki' => 'white',
            'DarkMagenta' => 'white',
            'DarkOliveGreen' => 'white',
            'DarkOrange' => 'white',
            'DarkOrchid' => 'white',
            'DarkRed' => 'white',
            'DarkSalmon' => 'white',
            'DarkSeaGreen' => 'white',
            'DarkSlateBlue' => 'white',
            'DarkSlateGray' => 'white',
            'DarkTurquoise' => 'white',
            'DarkViolet' => 'white',
            'DeepPink' => 'white',
            'DeepSkyBlue' => 'white',
            'DodgerBlue' => 'white',
            'ForestGreen' => 'white',
            'Fuchsia' => 'white',
            'Gold' => 'DimGray',
            'GoldenRod' => 'white',
            'Green' => 'white',
            'GreenYellow' => 'DimGray',
            'HotPink' => 'white',
            'IndianRed' => 'white',
            'Indigo' => 'white',
            'Khaki' => 'DimGray',
            'LawnGreen' => 'DimGray',
            'LemonChiffon' => 'DimGray',
            'LightBlue' => 'DimGray',
            'LightCoral' => 'white',
            'LightCyan' => 'DimGray',
            'LightGoldenRodYellow' => 'DimGray',
            'LightGreen' => 'DimGray',
            'LightPink' => 'DimGray',
            'LightSalmon' => 'white',
            'LightSeaGreen' => 'white',
            'LightSkyBlue' => 'DimGray',
            'LightSteelBlue' => 'DimGray',
            'Lime' => 'DimGray',
            'LimeGreen' => 'white',
            'Magenta' => 'white',
            'Maroon' => 'white',
            'MediumAquaMarine' => 'DimGray',
            'MediumBlue' => 'white',
            'MediumOrchid' => 'white',
            'MediumPurple' => 'white',
            'MediumSeaGreen' => 'white',
            'MediumSlateBlue' => 'white',
            'MediumSpringGreen' => 'DimGray',
            'MediumTurquoise' => 'white',
            'MediumVioletRed' => 'white',
            'MidnightBlue' => 'white',
            'MistyRose' => 'DimGray',
            'Moccasin' => 'DimGray',
            'Navy' => 'white',
            'Olive' => 'white',
            'OliveDrab' => 'white',
            'Orange' => 'white',
            'OrangeRed' => 'white',
            'Orchid' => 'white',
            'PaleGoldenRod' => 'DimGray',
            'PaleGreen' => 'DimGray',
            'PaleTurquoise' => 'DimGray',
            'PaleVioletRed' => 'white',
            'PeachPuff' => 'DimGray',
            'Peru' => 'white',
            'Pink' => 'DimGray',
            'Plum' => 'white',
            'PowderBlue' => 'DimGray',
            'Purple' => 'white',
            'RebeccaPurple' => 'white',
            'RosyBrown' => 'white',
            'RoyalBlue' => 'white',
            'SaddleBrown' => 'white',
            'Salmon' => 'white',
            'SandyBrown' => 'white',
            'SeaGreen' => 'white',
            'Sienna' => 'white',
            'SkyBlue' => 'white',
            'SlateBlue' => 'white',
            'SlateGray' => 'white',
            'SpringGreen' => 'DimGray',
            'SteelBlue' => 'white',
            'Tan' => 'DimGray',
            'Teal' => 'white',
            'Thistle' => 'DimGray',
            'Tomato' => 'white',
            'Turquoise' => 'DimGray',
            'Violet' => 'white',
            'Wheat' => 'DimGray',
            'Yellow' => 'DimGray',
            'YellowGreen' => 'white',
        ],
    ],

];
